use_frameworks!

platform :ios, '8.0'

target 'LEGOImageCropper_Example' do
  pod 'LEGOImageCropper', :path => '../'
  pod 'Masonry'
  target 'LEGOImageCropper_Tests' do
    inherit! :search_paths

    
  end
end
